# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            software...
tagline:          'things to know, things to see, things to learn'
description:      'My Blog about Software, Life and other things"' target="_blank">@lukstadler</a>.'
url:              http://lukstadler.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Lukas Stadler'
  url:            https://twitter.com/lukstadler

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/lukstadler/lukstadler.github.io
